import Foundation

struct EnrollmentLink: Decodable, Equatable {
    let endpoint: String
    let token: String

    var dashboard: String { URL(string: endpoint)?.host ?? "" }

    static func parse(_ text: String) throws -> EnrollmentLink {
        guard text.utf8.count <= 4096, let url = URL(string: text.trimmingCharacters(in: .whitespacesAndNewlines)),
              url.scheme == "familyvpn", url.host == "enroll", url.path.isEmpty,
              url.user == nil, url.password == nil, url.port == nil, url.query == nil,
              let fragment = url.fragment, !fragment.isEmpty,
              fragment.utf8.allSatisfy({ (65...90).contains($0) || (97...122).contains($0) || (48...57).contains($0) || $0 == 45 || $0 == 95 }) else {
            throw AppError.message("Use a device setup link generated by your Family VPN dashboard.")
        }
        var encoded = fragment.replacingOccurrences(of: "-", with: "+").replacingOccurrences(of: "_", with: "/")
        encoded += String(repeating: "=", count: (4 - encoded.count % 4) % 4)
        guard let data = Data(base64Encoded: encoded), let value = try? JSONDecoder().decode(Self.self, from: data),
              let endpoint = URL(string: value.endpoint), endpoint.scheme == "https", endpoint.host != nil,
              endpoint.user == nil, endpoint.password == nil, endpoint.query == nil, endpoint.fragment == nil,
              endpoint.port == nil || endpoint.port == 443,
              value.token.hasPrefix("invite_"), value.token.utf8.count == 50,
              value.token.dropFirst(7).utf8.allSatisfy({ (65...90).contains($0) || (97...122).contains($0) || (48...57).contains($0) || $0 == 45 || $0 == 95 }) else {
            throw AppError.message("This setup link is invalid. Generate a new code in your dashboard.")
        }
        _ = try WatchdogStatus.endpoint(from: endpoint)
        return value
    }
}
