version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies, github_actions]
    open-pull-requests-limit: 5
  - package-ecosystem: pip
    directories: [/, /family_vpn, /MyVPN/Watchdog]
    schedule:
      interval: weekly
    labels: [dependencies, python]
    groups:
      python-dependencies:
        patterns: ['*']
    open-pull-requests-limit: 5
  - package-ecosystem: docker
    directories: [/, /family_vpn]
    schedule:
      interval: weekly
    labels: [dependencies, containers]
    groups:
      container-bases:
        patterns: ['*']
    open-pull-requests-limit: 5
